### ISSUE TITLE
Couch potato full of errors. 

### ISSUE THREAD

**Issue by TH3-M0L3** [lsellens/service.downloadmanager.SickPotatoHead#6]
I have CP running on my HTPC as part of the sickpotatohead package and it's not been working properly for some time now. 

My logs are riddled with errors and I need some direction please to help me sort it out!

Openelec 5.08 - generic x86_64 - kernal: linux 3.17.8
Kodi 14.2 Git:7cc53a9
CP Version e9593f6 (8/31/2015, 8:55:08 PM) 
Updatersource, desktop

Please see my debug log at pastebin.
http://pastebin.com/zfzYTFdY

Please see my couchpotatoserver.ini for what it's worth.
http://pastebin.com/iNJNx3kq

Downloaded movies not marked as complete. Manually doing this doesn't work. As soon as the page is refreshed, they are back on the list

The above point is true for movies in the wanted list. When they are deleted and the page refreshed, the deleted wanted movie is back on the list

Searching, snatching and subsequent delivery of NZB to SAB doesn't work.

I manually find NZB's which I deliver to SAB myself. In order for me to get them scraped by CP, i generally restart CP and it might / might not work ok for long enough to do that bit. Manual folder scan doesn't work as it constantly reports that the renamer is already running.

Thanks, and thanks again for any help recieved.

**Comment by ryanmaule** [comment]
I have the same issue, CP won't load at all anymore.

**Comment by TH3-M0L3** [comment]
SSH into your machine
1. Delete your database folder
2. Reboot your system and CP should start
3. Re-scan your library
4. Manually rebuild your wanted list by adding the movies to it again

Yes, it's a schlep, but it worked for me. 

The other thing which I now have to do via ssh every time I need to reboot the machine is to rename my couchpotatoserver.ini file to anything I choose before I reboot the system. 

This then causes the cp to create a new .ini file with default settings. 
I then delete this, rename my original .ini file back again and restart cp only from its GUI. 

If I don't do this, CP will not start using the original .ini file.

**Comment by TH3-M0L3** [comment]
Just a note on the above, I'm using Audo, not sickpotatoehead

**Comment by TH3-M0L3** [comment]
Solved

Deleted database folder and resumed almost normal behaviour
